# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/code
  docker:
    # specify the version you desire here
    - image: circleci/android:api-26-alpha
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: update android sdk
          command: |
            echo y | android update sdk --no-ui --all --filter tool,extra-android-m2repository,extra-google-google_play_services,extra-google-m2repository,android-26
            echo y | android update sdk --no-ui --all --filter build-tools-26.0.2

      - run:
          name: download gradle dependencies
          command: ./gradlew androidDependencies

      - run:
          name: unit test
          command: |
            ./gradlew test
            ./gradlew lint test

      - run:
          name: Show list of system-images
          command: sdkmanager --list --verbose | grep system-images

      - run:
          name: Setup Emulator
          command: sdkmanager "system-images;android-24;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-24;default;armeabi-v7a"

      - run:
          name: Launch Emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true

      - run:
          name: Wait emulator
          command: |
            circle-android wait-for-boot
            adb shell input keyevent 82

      - run:
          name: Run Instrumentation test
          command: ./gradlew katsushika:connectedAndroidTest

      - store_test_results:
          path: example/build/test-results

      - store_artifacts:
          path: example/build/reports
          destination: reports

  deploy:
    <<: *defaults
    steps:
      - run:
          name: Distribute Bintray
          command: ./gradlew bintrayUpload

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master